# Basic Information 
title: Yubo Huang
title_zh: 黄昱博
position: Research Intern
affiliation: University of Alberta
affiliation_url: https://www.ualberta.ca/
email: yubo.huang@hotmail.com

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: Yubo Huang
description: Yubo Huang
canonical: https://yubohuangai.github.io/

# Links 
# If you don't need one of them, you may delete the corresponding line.
cv_link: assets/files/resume.pdf
github_link: https://github.com/yubohuangai
linkedin: https://www.linkedin.com/in/yubo-huang-716530296
google_scholar: https://scholar.google.ca/citations?user=qYREfhAAAAAJ&hl=en&authuser=2
# twitter: https://twitter.com/

# Profile picture and favicon
avatar: ./assets/img/avatar.png
favicon: ./assets/img/favicon.png

# Footnote ("Powered by Jekyll and Minimal Light theme.")
enable_footnote: true

# Font: "Serif" or "Sans Serif"
font: "Serif"

# Google Analytics ID
# google_analytics: UA-111540567-4

# Files removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
